#!/bin/bash

source ./config.properties
docker run --rm -it \
    -u $UID:$UID \
    -e XDG_CACHE_HOME=/tmp/.cache \
    -e GOPROXY=${GOPROXY} \
    -e CGO_ENABLED=0 \
    -e GOOS=${@: -1} \
    -e GOARCH=amd64 \
    -v $PWD:/srv/app \
    -v $PWD/packages:/go \
    -w /srv/app \
    golang:alpine go build ${@:1:$(($#-1))}